accounts:
  deployment:
    nodeSelector:
      a: b
    tolerations:
      - key: TaintKey
        operator: Equal
        value: TaintValue
        effect: NoSchedule
  devMode: true
  image:
    repository: ghcr.io/arikkfir/greenstar_fork/accounts
    tag: v3+forked
    pullPolicy: Always
  logLevel: info
  serviceAccount:
    annotations:
      a: b
redis:
  deployment:
    nodeSelector:
      a: b
    tolerations:
      - key: TaintKey
        operator: Equal
        value: TaintValue
        effect: NoSchedule
  image:
    repository: redis/redis-stack
    tag: 6.2.5
    pullPolicy: IfNotPresent
  serviceAccount:
    annotations:
      a: b
neo4j:
  deployment:
    nodeSelector:
      a: b
    tolerations:
      - key: TaintKey
        operator: Equal
        value: TaintValue
        effect: NoSchedule
  image:
    repository: neo4j
    tag: 5.3.0-enterprise
    pullPolicy: IfNotPresent
  serviceAccount:
    annotations:
      a: b
  extraEnv:
    - name: NEO4J_db_logs_query_enabled
      value: INFO
    - name: NEO4J_db_logs_query_threshold
      value: 3s
    - name: NEO4J_server_logs_gc_enabled
      value: "true"
txprocessor:
  deployment:
    nodeSelector:
      a: b
    tolerations:
      - key: TaintKey
        operator: Equal
        value: TaintValue
        effect: NoSchedule
  devMode: true
  image:
    repository: ghcr.io/arikkfir/greenstar_fork/txprocessor
    tag: v3+forked
    pullPolicy: Always
  logLevel: info
  serviceAccount:
    annotations:
      a: b
xlsconverter:
  deployment:
    nodeSelector:
      a: b
    tolerations:
      - key: TaintKey
        operator: Equal
        value: TaintValue
        effect: NoSchedule
  devMode: true
  image:
    repository: ghcr.io/arikkfir/greenstar_fork/xlsconverter
    tag: v3+forked
    pullPolicy: Always
  logLevel: info
  serviceAccount:
    annotations:
      a: b
xlsxprocessor:
  deployment:
    nodeSelector:
      a: b
    tolerations:
      - key: TaintKey
        operator: Equal
        value: TaintValue
        effect: NoSchedule
  devMode: true
  image:
    repository: ghcr.io/arikkfir/greenstar_fork/xlsxprocessor
    tag: v3+forked
    pullPolicy: Always
  logLevel: info
  serviceAccount:
    annotations:
      a: b
