version: 2
updates:

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(gha)"
      include: scope
    labels:
      - dependencies

  # NPM
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(frontend)"
    labels:
      - dependencies

  # Go
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(backend)"
    labels:
      - dependencies

  # Docker
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
