# nonk8s
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: platform
deploy:
  kubeContext: kind-greenstar
  helm:
    releases:
      - name: greenstar-traefik
        remoteChart: traefik
        repo: https://traefik.github.io/charts
        version: 23.2.0
        wait: true
        valuesFiles:
          - deploy/local/platform/traefik-values.yaml
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: app
requires:
  - configs: [platform]
build:
  local:
    concurrency: 0
    useBuildkit: true
    push: false
  artifacts:
    - image: ghcr.io/arikkfir/greenstar/backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/arikkfir/greenstar/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.debug
      sync:
        manual:
          - dest: /workspace
            src: public/**/*
          - dest: /workspace
            src: src/**/*
manifests:
  kustomize:
    paths:
      - deploy/local/app
deploy:
  tolerateFailuresUntilDeadline: true
  statusCheckDeadlineSeconds: 1200
  kubeContext: kind-greenstar
  kubectl:
    defaultNamespace: default
