# nonk8s
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: app
profiles:
  - name: traefik
    patches:
      - op: add
        path: /requires
        value: [ { path: deploy/etc/skaffold-traefik.yaml } ]
build:
  local:
    concurrency: 0
    useBuildkit: true
    push: false
  artifacts:
    - image: ghcr.io/arikkfir/greenstar/neo4j
      context: deploy/base/neo4j
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/arikkfir/greenstar/migrations
      context: migrations
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/arikkfir/greenstar/backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/arikkfir/greenstar/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.debug
      sync:
        manual:
          - dest: /workspace
            src: public/**/*
          - dest: /workspace
            src: src/**/*
manifests:
  kustomize:
    paths:
      - deploy/local
deploy:
  tolerateFailuresUntilDeadline: true
  statusCheckDeadlineSeconds: 1200
  kubeContext: kind-greenstar
  kubectl:
    defaultNamespace: default
    hooks:
      before:
        - host:
            command:
              - kubectl
              - delete
              - job
              - greenstar-migrations
              - --cascade=foreground
              - --ignore-not-found=true
              - --timeout=30s
              - --wait=true
