# nonk8s
apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: greenstar
build:
  local:
    concurrency: 0
    useBuildkit: true
    push: false
  artifacts:
    - image: ghcr.io/arik-kfir/greenstar/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.debug
      sync:
        manual:
          - dest: /workspace
            src: public/**/*
          - dest: /workspace
            src: src/**/*
    - image: ghcr.io/arik-kfir/greenstar/backend
      context: backend
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - deploy/local
deploy:
  tolerateFailuresUntilDeadline: true
  statusCheckDeadlineSeconds: 60
  kubectl:
    defaultNamespace: default
