# nonk8s
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: greenstar
build:
  local:
    concurrency: 0
    useBuildkit: true
  artifacts:
    - image: ghcr.io/arikkfir/greenstar/backend/admin
      context: backend
      docker:
        dockerfile: Dockerfile.admin
    - image: ghcr.io/arikkfir/greenstar/backend/auth
      context: backend
      docker:
        dockerfile: Dockerfile.auth
    - image: ghcr.io/arikkfir/greenstar/backend/operations
      context: backend
      docker:
        dockerfile: Dockerfile.operations
    - image: ghcr.io/arikkfir/greenstar/backend/public
      context: backend
      docker:
        dockerfile: Dockerfile.public
    - image: ghcr.io/arikkfir/greenstar/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
#    - image: ghcr.io/arikkfir/greenstar/backend/public
#      context: backend
#      docker:
#        dockerfile: Dockerfile.public
#    - image: ghcr.io/arikkfir/greenstar/backend/xlsconverter
#      context: backend
#      docker:
#        dockerfile: Dockerfile.xlsconverter
profiles:
  - name: prod
    activation:
      - env: SKAFFOLD_PROFILE=prod
    deploy:
      statusCheckDeadlineSeconds: 120
      statusCheck: true
    manifests:
      kustomize:
        paths:
          - deploy/prod
  - name: dev
    activation:
      - command: dev
    deploy:
      statusCheckDeadlineSeconds: 600
      statusCheck: true
    manifests:
      helm:
        releases:
          - name: greenstar-nats
            repo: https://nats-io.github.io/k8s/helm/charts/
            remoteChart: nats
            namespace: default
            wait: true
            skipTests: true
      kustomize:
        paths:
          - deploy/dev
    portForward:
      - resourceType: service
        resourceName: greenstar-frontend
        namespace: default
        port: http
        localPort: 3000
      - resourceType: service
        resourceName: greenstar-auth
        namespace: default
        port: http
        localPort: 8000
      - resourceType: service
        resourceName: greenstar-operations
        namespace: default
        port: http
        localPort: 8001
      - resourceType: service
        resourceName: greenstar-admin
        namespace: default
        port: http
        localPort: 8002
      - resourceType: service
        resourceName: greenstar-public
        namespace: default
        port: http
        localPort: 8003
      - resourceType: service
        resourceName: greenstar-redis
        namespace: default
        port: 6379
      - resourceType: service
        resourceName: greenstar-redis
        namespace: default
        port: http
        localPort: 9000
      - resourceType: service
        resourceName: greenstar-neo4j
        namespace: default
        port: 7687
      - resourceType: service
        resourceName: greenstar-neo4j
        namespace: default
        port: http
        localPort: 7474
    patches:
      - op: replace
        path: /build/artifacts/4/docker/dockerfile
        value: Dockerfile.debug
      - op: add
        path: /build/artifacts/4/sync
        value:
          manual:
            - dest: /workspace
              src: public/**/*
            - dest: /workspace
              src: src/**/*
