# nonk8s
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: greenstar
build:
  artifacts:
    - image: ghcr.io/arikkfir/greenstar/backend
      context: backend
      docker:
        buildArgs:
          VERSION: v0.0.0+{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        dockerfile: backend/Dockerfile.backend
        target: production
    - image: ghcr.io/arikkfir/greenstar/init-job
      context: backend
      docker:
        buildArgs:
          VERSION: v0.0.0+{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        dockerfile: backend/Dockerfile.initJob
        target: production
    - image: ghcr.io/arikkfir/greenstar/exchange-rates-job
      context: backend
      docker:
        buildArgs:
          VERSION: v0.0.0+{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        dockerfile: backend/Dockerfile.exchangeRatesJob
        target: production
    - image: ghcr.io/arikkfir/greenstar/frontend
      context: frontend
      docker:
        buildArgs:
          VERSION: v0.0.0+{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        dockerfile: frontend/Dockerfile.frontend
        target: development
      sync:
        manual:
          - src: src/**
            dest: /app/
  local:
    push: false
    useBuildkit: true
    concurrency: 1
deploy:
  helm:
    hooks:
      before:
        - host:
            command:
              - bash
              - -c
              - yq -e '[.frontend.extraEnv[] | select(.name == "VITE_DESCOPE_PROJECT_ID")] | length == 1' ./hack/greenstar-values.yaml || yq -i ".frontend.extraEnv += [{name:\"VITE_DESCOPE_PROJECT_ID\",value:\"${DESCOPE_PROJECT_ID}\"}]" ./hack/greenstar-values.yaml
              - yq -e '[.frontend.extraEnv[] | select(.name == "VITE_LOCATION_IQ_ACCESS_TOKEN")] | length == 1' ./hack/greenstar-values.yaml || yq -i ".frontend.extraEnv += [{name:\"VITE_LOCATION_IQ_ACCESS_TOKEN\",value:\"${LOCATION_IQ_ACCESS_TOKEN}\"}]" ./hack/greenstar-values.yaml
    releases:
      - name: '{{default (list "greenstar" (cmd "whoami") | join "-") .HELM_RELEASE_NAME}}'
        chartPath: ./deploy/chart
        packaged:
          appVersion: 0.0.0-{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        namespace: greenstar
        createNamespace: true
        wait: true
        upgradeOnChange: true
        valuesFiles:
          - deploy/local/chart-local-values.yaml
          - hack/greenstar-values.yaml
        setValueTemplates:
          backend:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_backend}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_backend}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_backend}}"
          initJob:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_init_job}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_init_job}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_init_job}}"
          exchangeRatesCronJob:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_exchange_rates_job}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_exchange_rates_job}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_exchange_rates_job}}"
          frontend:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_frontend}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_frontend}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_frontend}}"
