# nonk8s
apiVersion: skaffold/v3
kind: Config
metadata:
  name: greenstar
build:
  local:
    push: false
    concurrency: 2
    useBuildkit: true
  artifacts:
    - image: ghcr.io/arikkfir/greenstar/api
      docker:
        dockerfile: Dockerfile.api
    - image: ghcr.io/arikkfir/greenstar/xlsconverter
      docker:
        dockerfile: Dockerfile.xlsconverter
portForward:
  - resourceType: service
    resourceName: greenstar-api
    port: 80
    localPort: 8000
  - resourceType: service
    resourceName: greenstar-redis
    port: 6379
  - resourceType: service
    resourceName: greenstar-redis
    port: 80
    localPort: 8001
  - resourceType: service
    resourceName: greenstar-neo4j
    port: 7687
  - resourceType: service
    resourceName: greenstar-neo4j
    port: 80
    localPort: 7474
manifests:
  kustomize:
    paths:
      - deploy/dev
