apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.neo4j.serviceAccount }}
  {{- with .Values.neo4j.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
  labels:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: neo4j
  name: {{ printf "%s-neo4j" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: neo4j
  name: {{ printf "%s-neo4j" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: neo4j
      port: 7687
      protocol: TCP
      targetPort: neo4j
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: neo4j
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: neo4j
  name: {{ printf "%s-neo4j" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.neo4j.persistence.requests.storage | quote }}
    limits:
      storage: {{ .Values.neo4j.persistence.limits.storage | quote }}
  {{- if .Values.neo4j.persistence.storageClass }}
  storageClassName: {{ .Values.neo4j.persistence.storageClass | quote }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: neo4j
  name: {{ printf "%s-neo4j" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
      app.kubernetes.io/component: neo4j
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
        app.kubernetes.io/component: neo4j
    spec:
      containers:
        - image: {{ printf "%s:%s" .Values.neo4j.image.repository .Values.neo4j.image.tag | quote }}
          name: neo4j
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_server_metrics_jmx_enabled
              value: "false"
            - name: NEO4J_server_metrics_prometheus_enabled
              value: "true"
            - name: NEO4J_db_lock_acquisition_timeout
              value: 10s
            - name: NEO4J_initial_dbms_default__database
              value: greenstar
            - name: NEO4J_server_panic_shutdown__on__panic
              value: "true"
            - name: NEO4J_server_memory_heap_initial__size
              value: {{ .Values.neo4j.heap.initialSize | quote }}
            - name: NEO4J_server_memory_heap_max__size
              value: {{ .Values.neo4j.heap.maxSize | quote }}
            - name: NEO4J_server_memory_off__heap_max__size
              value: {{ .Values.neo4j.offHeap.maxSize | quote }}
            - name: NEO4J_server_memory_pagecache_size
              value: {{ .Values.neo4j.pageCache.size | quote }}
            - name: NEO4J_dbms_security_auth__enabled
              value: "false"
            {{- range .Values.neo4j.extraEnv }}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          ports:
            - containerPort: 2004
              name: metrics
            - containerPort: 7687
              name: neo4j
            - containerPort: 7474
              name: http
          resources:
            limits:
              cpu: {{ .Values.neo4j.resources.limits.cpu | quote }}
              memory: {{ .Values.neo4j.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.neo4j.resources.requests.cpu | quote }}
              memory: {{ .Values.neo4j.resources.requests.memory | quote }}
          volumeMounts:
            - mountPath: /data
              name: data
      serviceAccountName: {{ printf "%s-neo4j" .Release.Name | quote }}
      {{- with .Values.neo4j.deployment.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.neo4j.deployment.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s-neo4j" .Release.Name | quote }}
