apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.redis.serviceAccount }}
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
  labels:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: redis
  name: {{ printf "%s-redis" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: redis
  name: {{ printf "%s-redis" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name | quote }}
    app.kubernetes.io/component: redis
  name: {{ printf "%s-redis" .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
      app.kubernetes.io/component: redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - image: {{ printf "%s:%s" .Values.redis.image.repository .Values.redis.image.tag | quote }}
          name: redis
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 8001
              name: http
          resources:
            limits:
              cpu: {{ .Values.redis.resources.limits.cpu | quote }}
              memory: {{ .Values.redis.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
              memory: {{ .Values.redis.resources.requests.memory | quote }}
      serviceAccountName: {{ printf "%s-redis" .Release.Name | quote }}
      {{- with .Values.redis.deployment.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.deployment.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
