apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: client-nontls
      port: 6379
      protocol: TCP
      targetPort: client-nontls
  selector:
    app.kubernetes.io/name: redis
  type: ClusterIP
