{{- $prefix := include "greenstar.prefix" . -}}
{{- /*------------------------------------------------------------------------------------------------------------*/ -}}
---

{{- range .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if not (empty .annotations) }}
  annotations:
    {{ range $name, $value := .annotations -}}
    {{ $name }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
{{/*    {{- include "greenstar.commonLabels" . | nindent 4 }}*/}}
    app.kubernetes.io/component: {{ .component | quote }}
    {{- if not (empty .labels) }}
    {{ range $name, $value := .labels -}}
    {{ $name }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  name: {{ .name | quote }}
data:
{{ .data | toYaml | indent 2 }}
{{- end }}
