{{- $prefix := include "greenstar.prefix" . -}}
{{- $componentName := "oidc" -}}
{{- /*------------------------------------------------------------------------------------------------------------*/ -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "greenstar.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $componentName | quote }}
  name: "gcp-oidc"
data:
  credential-configuration.json: {{ required "GCP OIDC credentials is required" .Values.oidc.gcp.config | quote }}
