apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  ports:
    - name: client-nontls
      port: 7687
      protocol: TCP
      targetPort: client-nontls
    - name: http
      port: 7474
      protocol: TCP
      targetPort: http
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: neo4j-tls
spec:
  entryPoints: [ bolt ]
  routes:
    - match: HostSNI(`neo4j.${deploy_environment}.greenstar.kfirs.com`)
      middlewares:
        - name: ip-whitelist-tcp
          namespace: traefik
      services:
        - name: neo4j
          port: client-nontls
  tls:
    secretName: greenstar-wildcard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: neo4j
spec:
  entryPoints: [ websecure ]
  routes:
    - kind: Rule
      match: Host(`neo4j.${deploy_environment}.greenstar.kfirs.com`)
      middlewares:
        - name: ip-whitelist
          namespace: traefik
      priority: 100
      services:
        - name: neo4j
          port: http
          kind: Service
  tls:
    secretName: greenstar-wildcard-tls # Keep the "greenstar-" prefix here; kustomize does not know to add it here
