apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: neo4j
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neo4j
    spec:
      containers:
        - image: neo4j:5.3-enterprise
          name: neo4j
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_server_metrics_jmx_enabled
              value: "false"
            - name: NEO4J_server_metrics_prometheus_enabled
              value: "true"
            - name: NEO4J_db_lock_acquisition_timeout
              value: 10s
            - name: NEO4J_server_panic_shutdown__on__panic
              value: "true"
            - name: NEO4J_server_memory_heap_initial__size
              value: 512m
            - name: NEO4J_server_memory_heap_max__size
              value: 512m
            - name: NEO4J_server_memory_off__heap_max__size
              value: 256m
            - name: NEO4J_server_memory_pagecache_size
              value: 128m
            - name: NEO4J_dbms_security_auth__enabled
              value: "false"
          ports:
            - containerPort: 2004
              name: metrics
            - containerPort: 7687
              name: client-nontls
            - containerPort: 7474
              name: http
          startupProbe:
            exec:
              command:
                - /var/lib/neo4j/bin/cypher-shell
                - --non-interactive
                - SHOW DATABASES
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 1
            successThreshold: 1
            terminationGracePeriodSeconds: 120
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /var/lib/neo4j/bin/cypher-shell
                - --non-interactive
                - SHOW DATABASES
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
            terminationGracePeriodSeconds: 60
            timeoutSeconds: 15
          resources:
            limits:
              cpu: 2000m
              memory: 1500Mi
            requests:
              cpu: 2000m
              memory: 1500Mi
          volumeMounts:
            - mountPath: /backups
              name: backups
              readOnly: false
            - mountPath: /data
              name: data
              readOnly: false
            - mountPath: /import
              name: import
              readOnly: false
            - mountPath: /logs
              name: logs
              readOnly: false
            - mountPath: /metrics
              name: metrics
              readOnly: false
            - mountPath: /plugins
              name: plugins
              readOnly: false
      enableServiceLinks: false
      serviceAccountName: neo4j
      volumes:
        - name: backups
          persistentVolumeClaim:
            claimName: neo4j-backups
            readOnly: false
        - name: data
          persistentVolumeClaim:
            claimName: neo4j-data
            readOnly: false
        - name: import
          persistentVolumeClaim:
            claimName: neo4j-import
            readOnly: false
        - name: logs
          persistentVolumeClaim:
            claimName: neo4j-logs
            readOnly: false
        - name: metrics
          persistentVolumeClaim:
            claimName: neo4j-metrics
            readOnly: false
        - name: plugins
          persistentVolumeClaim:
            claimName: neo4j-plugins
            readOnly: false
