apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - grafana-httproute.yaml
  - jaeger-httproute.yaml
  - jaeger-instance.yaml
  - prometheus-httproute.yaml
