apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/version: 0.0.0-local
resources:
  - ../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/role=microservice
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: warn
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEV_MODE
          value: "false"
