observability:
  logging:
    level: trace

ingress:
  domain: greenstar.test

backend:
  extraEnv:
    - name: OTEL_METRICS_EXPORTER
      value: "prometheus"
    - name: OTEL_LOGS_EXPORTER
      value: "none"
    - name: OTEL_EXPORTER_PROMETHEUS_HOST
      value: "0.0.0.0"
    - name: OTEL_EXPORTER_PROMETHEUS_PORT
      value: "8000"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: "http://jaeger-all-in-one.observability.svc.cluster.local:4318/v1/traces"
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure

exchangeRatesCronJob:
  extraEnv:
    - name: OTEL_METRICS_EXPORTER
      value: "prometheus"
    - name: OTEL_LOGS_EXPORTER
      value: "none"
    - name: OTEL_EXPORTER_PROMETHEUS_HOST
      value: "0.0.0.0"
    - name: OTEL_EXPORTER_PROMETHEUS_PORT
      value: "8000"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: "http://jaeger-all-in-one.observability.svc.cluster.local:4318/v1/traces"

frontend:
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure

initJob:
  extraEnv:
    - name: GENERATE_SAMPLE_DATA
      value: "T"
    - name: OTEL_METRICS_EXPORTER
      value: "prometheus"
    - name: OTEL_LOGS_EXPORTER
      value: "none"
    - name: OTEL_EXPORTER_PROMETHEUS_HOST
      value: "0.0.0.0" # we should modify jobs to PUSH metrics instead of using pull (when OTEL supports it)
    - name: OTEL_EXPORTER_PROMETHEUS_PORT
      value: "8000"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: "http://jaeger-all-in-one.observability.svc.cluster.local:4318/v1/traces"

postgres:
  backendPassword: "local"
  extraArgs:
    - -c
    - log_statement=mod
  extraUsers:
    local: local
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      tlsSectionName: postgres
