observability:
  logging:
    level: trace

ingress:
  domain: greenstar.test

backend:
  extraEnv:
    OTEL_SDK_DISABLED:
      value: "true"
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure

exchangeRatesCronJob:
  extraEnv:
    OTEL_SDK_DISABLED:
      value: "true"

frontend:
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure

initJob:
  extraEnv:
    OTEL_SDK_DISABLED:
      value: "true"
  volumes:
    - name: rates
      hostPath:
        path: /var/greenstar/rates
        type: Directory
  volumeMounts:
    - name: rates
      mountPath: /var/greenstar/rates

postgres:
  backendPassword: "local"
  extraArgs:
    - -c
    - log_statement=mod
  extraUsers:
    local: local
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      tlsSectionName: postgres
