observability:
  logging:
    level: trace
    format: text

ingress:
  domain: greenstar.test

backend:
  extraEnv:
    OTEL_METRICS_EXPORTER:
      value: "prometheus"
    OTEL_LOGS_EXPORTER:
      value: "none"
    OTEL_EXPORTER_PROMETHEUS_HOST:
      value: "0.0.0.0" # we should modify jobs to PUSH metrics instead of using pull (when OTEL supports it)
    OTEL_EXPORTER_PROMETHEUS_PORT:
      value: "8000"
    OTEL_TRACES_EXPORTER:
      value: "otlp"
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:
      value: "http://jaeger-all-in-one.observability.svc.cluster.local:4318/v1/traces"
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure

exchangeRatesCronJob:
  extraEnv:
    OTEL_METRICS_EXPORTER:
      value: "prometheus"
    OTEL_LOGS_EXPORTER:
      value: "none"
    OTEL_EXPORTER_PROMETHEUS_HOST:
      value: "0.0.0.0" # we should modify jobs to PUSH metrics instead of using pull (when OTEL supports it)
    OTEL_EXPORTER_PROMETHEUS_PORT:
      value: "8000"
    OTEL_TRACES_EXPORTER:
      value: "otlp"
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:
      value: "http://jaeger-all-in-one.observability.svc.cluster.local:4318/v1/traces"

frontend:
  extraArgs: [ "--", "--logLevel=info", "--port=3000", "--host=0.0.0.0" ]
  extraEnv:
    VITE_SLOW_REQUESTS:
      value: "F"
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  readinessProbe: false
  livenessProbe: false
  startupProbe: false

initJob:
  extraEnv:
    OTEL_METRICS_EXPORTER:
      value: "prometheus"
    OTEL_LOGS_EXPORTER:
      value: "none"
    OTEL_EXPORTER_PROMETHEUS_HOST:
      value: "0.0.0.0" # we should modify jobs to PUSH metrics instead of using pull (when OTEL supports it)
    OTEL_EXPORTER_PROMETHEUS_PORT:
      value: "8000"
    OTEL_TRACES_EXPORTER:
      value: "otlp"
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:
      value: "http://jaeger-all-in-one.observability.svc.cluster.local:4318/v1/traces"

postgres:
  backendPassword: "local"
  extraArgs:
    - -c
    - log_statement=mod
  extraUsers:
    local: local
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      tlsSectionName: postgres
  initJobPassword: "local"
  initPassword: "local"
