apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jaeger-operator-ingress
  namespace: observability
  labels:
    app.kubernetes.io/instance: jaeger-operator
    app.kubernetes.io/managed-by: devex
    app.kubernetes.io/name: jaeger-operator
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-ingress
  namespace: observability
  labels:
    app.kubernetes.io/instance: jaeger-operator
    app.kubernetes.io/managed-by: devex
    app.kubernetes.io/name: jaeger-operator
subjects:
  - kind: ServiceAccount
    namespace: observability
    name: jaeger-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jaeger-operator-ingress
