apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: greenstar-backend-config
    behavior: create
    envs: [ backend-config.env ]
  - name: greenstar-frontend-config
    behavior: create
    envs: [ frontend-config.env ]
secretGenerator:
  - name: greenstar-backend-secrets
    behavior: create
    envs: [ backend-secrets.env ]
  - name: greenstar-frontend-secrets
    behavior: create
    envs: [ frontend-secrets.env ]
  - name: greenstar-wildcard-tls
    type: kubernetes.io/tls
    behavior: create
    files:
      - tls.crt=_wildcard.greenstar.test.pem
      - tls.key=_wildcard.greenstar.test-key.pem
patches:

  # Backend patches
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/component=backend
    patch: |-

      # additional environment variables from .env files 
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: greenstar-backend-config
              optional: false
          - secretRef:
              name: greenstar-backend-secrets
              optional: false

      # locally more memory is required when running Go in debug mode
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi

      # exclude some headers from the access log when running locally
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-exclude-remote-addr
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=accept.*
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=access-control-.*
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=authorization
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=content-.*
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=cookie
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=origin
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=referer
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=user-agent
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=x-forwarded-.*
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --http.access-log-excluded-headers=x-real-ip

  # Frontend patches
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/component=frontend
    patch: |-

      # disable skaffold debug for frontend (no need to debug node.js)
      - op: add
        path: /spec/template/metadata/annotations
        value:
          debug.cloud.google.com/config: "{}"

      # additional environment variables from .env files 
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: greenstar-frontend-config
              optional: false
          - secretRef:
              name: greenstar-frontend-secrets
              optional: false

      # locally it takes longer to start, since it compiles it on the fly (and not during image build time)
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
        value: 30
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
        value: 30
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/timeoutSeconds
        value: 120

      # locally more memory is required since we run the React server itself instead of NGINX with static files
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      
      # since we request much more memory, local cluster might not have enough memory to have 2 pods running at once
      - op: replace
        path: /spec/strategy/type
        value: Recreate
