apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: greenstar-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: greenstar-backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: greenstar-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
    spec:
      containers:
        - image: ghcr.io/arikkfir/greenstar/backend
          name: backend
          env:
            - name: NEO4J_HOST
              value: greenstar-neo4j
            - name: REDIS_HOST
              value: greenstar-redis
            - name: AUTH_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: greenstar-google-app
                  optional: false
            - name: AUTH_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: greenstar-google-app
                  optional: false
          startupProbe:
            httpGet:
              port: http
              path: /healthz
            failureThreshold: 30
            periodSeconds: 10
            terminationGracePeriodSeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
            failureThreshold: 3
            periodSeconds: 3
            terminationGracePeriodSeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 16Mi
      serviceAccountName: greenstar-backend
