apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: greenstar-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: greenstar-frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: greenstar-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - image: ghcr.io/arikkfir/greenstar/frontend
          name: frontend
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 512Mi
      serviceAccountName: greenstar-frontend
