apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: greenstar
  app.kubernetes.io/name: greenstar
  app.kubernetes.io/managed-by: kustomize
resources:
  - admin.yaml
  - auth.yaml
  - frontend.yaml
  - neo4j.yaml
  - operations.yaml
  - public.yaml
  - redis.yaml
