apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: greenstar
namePrefix: greenstar-
resources:
  - dns
  - secrets
  - redis
  - neo4j
  - api
  - frontend
configurations:
  - kustomizeconfig.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node.kfirs.com/role: work
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - effect: NoExecute
            key: node.kfirs.com/role
            operator: Equal
            value: work
    target:
      group: apps
      version: v1
      kind: Deployment
