apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: api
namePrefix: api-
resources:
  - rbac.yaml
  - secrets.yaml
  - service.yaml
  - deployment.yaml
