apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: greenstar-api@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: backend
  name: backend
