apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: descope
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: SecretStore
    name: greenstar-gcp
  data:
    - secretKey: AUTH_DESCOPE_PROJECT_ID
      remoteRef:
        key: greenstar-descope-project-id
    - secretKey: AUTH_DESCOPE_MANAGEMENT_KEY
      remoteRef:
        key: greenstar-descope-management-key
