apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: backend
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
spec:
  entryPoints: [ websecure ]
  routes:
    - kind: Rule
      match: Host(`api.${deploy_environment}.greenstar.kfirs.com`)
      priority: 100
      services:
        - name: backend
          port: http
          kind: Service
  tls:
    secretName: greenstar-wildcard-tls # Keep the "greenstar-" prefix here; kustomize does not know to add it here
