apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${flux_environment}
resources:
  - ../base
  - certificate.yaml
  - dnsrecord.yaml
  - gcp-iam.yaml
  - secrets.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/component=backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: greenstar-descope
              optional: false
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRouteTCP
      name: redis-tls-tcp
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: HostSNI(`redis.${flux_environment}.greenstar.kfirs.com`)
      - op: add
        path: /spec/routes/0/middlewares
        value:
          - name: ip-whitelist-tcp
            namespace: traefik
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: neo4j-tls
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`neo4j.${flux_environment}.greenstar.kfirs.com`)
      - op: add
        path: /spec/routes/0/middlewares
        value:
          - name: ip-whitelist
            namespace: traefik
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRouteTCP
      name: neo4j-tls-tcp
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: HostSNI(`neo4j.${flux_environment}.greenstar.kfirs.com`)
      - op: add
        path: /spec/routes/0/middlewares
        value:
          - name: ip-whitelist-tcp
            namespace: traefik
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: backend-tls
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`api.${flux_environment}.greenstar.kfirs.com`)
      - op: add
        path: /spec/routes/0/middlewares
        value:
          - name: ip-whitelist
            namespace: traefik
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: frontend-tls
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: HostRegexp(`{tenant:[a-zA-Z][a-zA-Z0-9_-]*}.${flux_environment}.greenstar.kfirs.com`)
      - op: add
        path: /spec/routes/0/middlewares
        value:
          - name: ip-whitelist
            namespace: traefik
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node.kfirs.com/role: work
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - effect: NoExecute
            key: node.kfirs.com/role
            operator: Equal
            value: work
  - target:
      group: apps
      version: v1
      kind: Job
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node.kfirs.com/role: work
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - effect: NoExecute
            key: node.kfirs.com/role
            operator: Equal
            value: work
