apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: greenstar-gcpsm
spec:
  provider:
    gcpsm:
      projectID: arikkfir
      auth:
        workloadIdentity:
          clusterLocation: me-west1-a
          clusterName: main
          serviceAccountRef:
            name: greenstar-backend # TODO: use a dedicated SA for secrets instead of the backend SA
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: greenstar-descope
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: SecretStore
    name: greenstar-gcpsm
  data:
    - secretKey: AUTH_DESCOPE_PROJECT_ID
      remoteRef:
        key: greenstar-descope-project-id
    - secretKey: AUTH_DESCOPE_MANAGEMENT_KEY
      remoteRef:
        key: greenstar-descope-management-key
