apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: frontend
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-tls
spec:
  entryPoints: [websecure]
  routes:
    - kind: Rule
      match: HostRegexp(`{tenant:[a-zA-Z][a-zA-Z0-9_-]*}.greenstar.test`)
      services:
        - name: frontend
          port: http
          kind: Service
  tls:
    secretName: greenstar-wildcard-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        debug.cloud.google.com/config: "{}"
      labels:
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - image: ghcr.io/arikkfir/greenstar/frontend
          name: frontend
          env: []
          envFrom:
            - configMapRef:
                name: frontend-config
                optional: false
            - secretRef:
                name: frontend-secrets
                optional: false
          livenessProbe:
            httpGet:
              port: http
              path: /index.html
            failureThreshold: 3
            periodSeconds: 30
            terminationGracePeriodSeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              port: http
              path: /index.html
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 64Gi
            requests:
              cpu: 200m
              memory: 32Mi
          startupProbe:
            httpGet:
              port: http
              path: /index.html
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 1
      enableServiceLinks: false
      serviceAccountName: frontend
