apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: app
resources:
  - backend.yaml
  - frontend.yaml
  - migrations.yaml
configurations:
  - kustomizeconfig.yaml
