apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: migrations
  name: migrations
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: migrations
  name: migrations
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: migrations
    spec:
      containers:
        - image: neo4j:5.3-enterprise
          command:
            - bash
          args:
            - migrate.sh
          workingDir: /migrations
          name: migrations
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: migrations
              mountPath: /migrations
              readOnly: true
      enableServiceLinks: false
      restartPolicy: OnFailure
      serviceAccountName: migrations
      volumes:
        - name: migrations
          configMap:
            name: greenstar-app-migrations
            optional: false
            defaultMode: 0444
  ttlSecondsAfterFinished: 1200
