# nonk8s
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: traefik
deploy:
  kubeContext: kind-greenstar
  helm:
    releases:
      - name: greenstar-traefik
        remoteChart: traefik
        repo: https://traefik.github.io/charts
        version: 23.2.0
        namespace: default
        wait: true
        valuesFiles:
          - deploy/etc/traefik-values.yaml
