apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
spec:
  entryPoints: [ websecure ]
  routes:
    - kind: Rule
      match: HostRegexp(`{tenant:[a-zA-Z][a-zA-Z0-9_-]*}.${deploy_environment}.greenstar.kfirs.com`)
      priority: 90
      services:
        - name: frontend
          port: http
          kind: Service
  tls:
    secretName: greenstar-wildcard-tls
