name: Build

on:
  push:
    branches:
      - '*'

jobs:

  docker:
    strategy:
      matrix:
        image: [ backend, frontend, neo4j, migrations ]
      fail-fast: false
    name: Build ${{ matrix.image }} image
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - if: matrix.image == 'frontend'
        run: |-
          cat > frontend/apply-patches.sh <<PATCHES_EOF
          ${{ secrets.FRONTEND_PATCHES }}
          PATCHES_EOF
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=sha,prefix=,suffix=,format=long
            type=ref,event=branch
            type=ref,event=pr
      - uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
