name: Automatic deployment

on:
  push:
    branches:
      - main

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:

  deploy-to-environment:
    name: Deploy
    uses: arikkfir/delivery/.github/workflows/deploy-to-environment.yml@main
    with:
      branch: ${{ github.ref_name }}
      images: |-
        ghcr.io/${{ github.repository }}/backend: ${{ github.sha }}
        ghcr.io/${{ github.repository }}/frontend: ${{ github.sha }}
        ghcr.io/${{ github.repository }}/migrations: ${{ github.sha }}
        ghcr.io/${{ github.repository }}/neo4j: ${{ github.sha }}
    secrets: inherit
