name: Automatic deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:

  deploy-to-environment:
    name: Deploy
    uses: arikkfir/delivery/.github/workflows/deploy-to-environment.yml@main
    concurrency:
      group: deployment
      cancel-in-progress: false
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      images: |-
        ghcr.io/${{ github.repository }}/backend: ${{ github.event.pull_request.head.sha || github.sha }}
        ghcr.io/${{ github.repository }}/frontend: ${{ github.event.pull_request.head.sha || github.sha }}
        ghcr.io/${{ github.repository }}/migrations: ${{ github.event.pull_request.head.sha || github.sha }}
        ghcr.io/${{ github.repository }}/neo4j: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit
