name: On push to branch
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:

  backend-unit-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - run: go test ./...
        working-directory: backend

  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    permissions:
      packages: write
    strategy:
      matrix:
        service: [ backend, frontend ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=sha,prefix=,suffix=,format=long
            type=ref,event=branch
            type=ref,event=pr
      - uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

#  deploy-to-environment:
#    name: Deploy to environment
#    needs: build-docker-images
#    uses: arik-kfir/delivery/.github/workflows/deploy-app-env.yml@main
#    concurrency:
#      group: deployment
#      cancel-in-progress: false
#    with:
#      environment: ${{ github.ref_name }}
#      images: |-
#        ghcr.io/${{ github.repository }}/admin/api: ${{ github.sha }}
#        ghcr.io/${{ github.repository }}/admin/frontend: ${{ github.sha }}
#        ghcr.io/${{ github.repository }}/app/api: ${{ github.sha }}
#        ghcr.io/${{ github.repository }}/app/frontend: ${{ github.sha }}
#        ghcr.io/${{ github.repository }}/operations/api: ${{ github.sha }}
#        ghcr.io/${{ github.repository }}/operations/frontend: ${{ github.sha }}
#    secrets: inherit
