name: Deploy PR

on:
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  env:
    name: Environment
    runs-on: ubuntu-22.04
    outputs:
      name: ${{ steps.env.outputs.name }}
    steps:
      - id: env
        uses: arikkfir/delivery-env-name@v1
        with:
          branch: ${{ github.event.pull_request.head.ref }}

  deploy:
    name: Deploy
    needs: env
    runs-on: ubuntu-22.04
    environment:
      name: ${{ needs.env.outputs.name }}
      url: https://acme.${{ needs.env.outputs.name }}.greenstar.kfirs.com
    steps:
      - uses: arikkfir/deploy@22db8e0bdd18893f795672714ad9146a8a35e117
        timeout-minutes: 15
        with:
          repository: greenstar
          branch: ${{ github.event.pull_request.head.ref }}
          sha: ${{ github.event.pull_request.head.sha }}
          environment: ${{ needs.env.outputs.name }}
          token: ${{ secrets.ARIKKFIR_GHA_AUTOMATION }}
