name: Deploy

on:
  issue_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:

  debug:
    name: Debug
    runs-on: ubuntu-22.04
    steps:
      - run: |
          cat <<EOF
          ${{ github.event }}
          EOF

  deploy:
    name: Deploy
    needs: debug
    uses: arikkfir/delivery/.github/workflows/deploy-to-environment.yml@main
    if: github.event_name == 'pull_request' || (github.event.issue.pull_request && github.event.comment.body == '/deploy')
    with:
      branch: ${{ github.head_ref || github.event.issue.pull_request.head.ref }}
      images: |-
        ghcr.io/${{ github.repository }}/backend: ${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}
        ghcr.io/${{ github.repository }}/frontend: ${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}
        ghcr.io/${{ github.repository }}/migrations: ${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}
        ghcr.io/${{ github.repository }}/neo4j: ${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}
    secrets: inherit
