name: Undeploy

on:
  pull_request:
    types: [ closed ]

jobs:

  undeploy:
    name: Undeploy from environment
    runs-on: ubuntu-22.04
    steps:
      - id: env
        uses: arikkfir/delivery-env-name@v1
        with:
          branch: ${{ github.event.pull_request.head.ref }}
      - uses: arikkfir/undeploy@main
        with:
          repository: greenstar
          environment: ${{ steps.env.outputs.name }}
          branch: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.ARIKKFIR_GHA_AUTOMATION }}
