name: Undeploy

on:
  pull_request:
    types: [ closed ]

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:

  undeploy:
    name: Undeploy from environment
    uses: arikkfir/delivery/.github/workflows/undeploy-from-environment.yml@main
    with:
      branch: ${{ github.head_ref }}
      images: |-
        ghcr.io/${{ github.repository }}/backend
        ghcr.io/${{ github.repository }}/frontend
        ghcr.io/${{ github.repository }}/migrations
        ghcr.io/${{ github.repository }}/neo4j
    secrets: inherit
