name: Update Exchange Rates

on:
#  schedule:
#    - '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  update-currencies-file:
    name: Update exchange rates file
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:

      - name: Fetch GreenSTAR secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          CURRENCY_API_KEY: "op://GreenSTAR/Currency API/credential"
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_GREENSTAR }}

      - name: Fetch Development secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          DEPLOY_KEY: "op://Development/Recurring GitHub Jobs Deploy Key/private key?ssh-format=openssh"
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_DEVELOPMENT }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ env.DEPLOY_KEY }}

      - name: Download currencies CSV
        run: |
          echo "TS=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          curl -G https://api.currencyapi.com/v3/currencies -H "apikey: ${CURRENCY_API_KEY}" | jq -r ".data | to_entries[] | [.value.code, \"$(date +'%Y-%m-%d %H:%M:%S')\", \"$(date +'%Y-%m-%d %H:%M:%S')\", .value.symbol, .value.symbol_native, .value.name, .value.decimal_digits, .value.rounding, .value.name_plural, .value.type, \"{\" + (.value.countries | join(\",\")) + \"}\"] | @csv" > ./deploy/local/currencies.csv

      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: './deploy/local/currencies.csv'
          message: "Update exchange rates currencies file"
