name: Update Exchange Rates

on:
#  schedule:
#    - '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  update-currencies-file:
    name: Update exchange rates file
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:

      - name: Fetch secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          CURRENCY_API_KEY: "op://GreenSTAR/Currency API/credential"
          DEPLOY_KEY: "op://Development/Recurring GitHub Jobs Deploy Key/private key?ssh-format=openssh"
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ env.DEPLOY_KEY }}

      - name: Download currencies
        run: |
          curl -G -o ./deploy/local/currencies.json https://api.currencyapi.com/v3/currencies -H "apikey: ${CURRENCY_API_KEY}"

      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: './deploy/local/currencies.json'
          message: "Update exchange rates currencies file"
