name: Verify
on:
  push:
    branches: ["*"]
defaults:
  run:
    shell: bash -euxo pipefail {0}
jobs:
  backend-unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - run: go test ./...
        working-directory: backend

  build-docker-images:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
      matrix:
        image: [backend, frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/arikkfir/${{ github.repository }}/${{ matrix.image }}
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=ref,event=branch
            type=ref,event=pr
      - uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  e2e-tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.17.0
          config: deploy/kind/cluster-config.yaml
          wait: 600s
      - run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
      - run: kubectl wait --for=condition=available -n ingress-nginx deploy/ingress-nginx-controller
      - run: kubectl wait -n ingress-nginx job/ingress-nginx-admission-create --for=condition=complete
      - run: kubectl wait -n ingress-nginx job/ingress-nginx-admission-patch --for=condition=complete
      - run: sleep 30
      - run: |-
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v2.2.0/skaffold-linux-amd64 \
            && chmod +x skaffold \
            && sudo mv skaffold /usr/local/bin \
            && skaffold version
      - run: |-
          cat > build.json <<EOF
          {
            "builds": [
              {
                "imageName": "ghcr.io/arikkfir/greenstar/frontend",
                "tag": "ghcr.io/arikkfir/greenstar/frontend:${{ github.sha }}"
              },
              {
                "imageName": "ghcr.io/arikkfir/greenstar/backend",
                "tag": "ghcr.io/arikkfir/greenstar/backend:${{ github.sha }}"
              }
            ]
          }
          EOF
      - run: skaffold deploy --tolerate-failures-until-deadline=true --build-artifacts=build.json
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      - run: kubectl get pod -A
      - run: curl -i http://localhost/auth/google/login
      - run: curl -i http://localhost/api/operations/
      - run: curl -i http://localhost/index.html
      - run: skaffold delete
