name: Verify

on:
  push:
    branches:
      - '*'

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:

  backend-format:
    name: Backend Go Fmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - run: |
          go fmt ./... | tee output.txt
          if [[ -s output.txt ]]; then
            echo "Incorrect Go formatting detected."
            exit 1
          fi
        working-directory: backend

  backend-unit-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - run: go test ./...
        working-directory: backend
