nameReference:
  - kind: ServiceAccount
    version: v1
    fieldSpecs:
      - group: external-secrets.io
        version: v1beta1
        kind: SecretStore
        path: spec/provider/gcpsm/auth/workloadIdentity/serviceAccountRef/name
  - group: iam.cnrm.cloud.google.com
    version: v1beta1
    kind: IAMServiceAccount
    fieldSpecs:
      - group: iam.cnrm.cloud.google.com
        version: v1beta1
        kind: IAMPolicyMember
        path: spec/memberFrom/serviceAccountRef/name
      - group: iam.cnrm.cloud.google.com
        version: v1beta1
        kind: IAMPolicyMember
        path: spec/resourceRef/name
