apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: greenstar-secrets@arikkfir.iam.gserviceaccount.com
  name: secrets
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: secrets
spec:
  displayName: GreenSTAR Secrets Accessor
  description: Used by the GreenSTAR GKE Secret Store to access GCP secrets.
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: secrets-ksa-link
spec:
  member: serviceAccount:arikkfir.svc.id.goog[${deploy_environment}/greenstar-secrets]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: secrets
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: secrets-secret-viewer
spec:
  memberFrom:
    serviceAccountRef:
      name: secrets
  role: roles/secretmanager.viewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/arikkfir
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: secrets-secret-accessor
spec:
  memberFrom:
    serviceAccountRef:
      name: secrets
  role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/arikkfir
