apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp
spec:
  provider:
    gcpsm:
      projectID: arikkfir
      auth:
        workloadIdentity:
          clusterLocation: me-west1-a
          clusterName: main
          serviceAccountRef:
            name: secrets
